name: Benchmark Check

on:
  push:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: indexd_benchmark
          POSTGRES_PASSWORD: indexd_benchmark
          POSTGRES_DB: indexd_benchmark
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_USER: indexd_benchmark
      POSTGRES_PASSWORD: indexd_benchmark
      POSTGRES_DB: indexd_benchmark
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '1.26'

      - name: Run benchmarks
        run: |
          set -euo pipefail
      
          if ! go test -run='^$' -benchmem -benchtime=200x -bench=. -timeout=2h ./... 2>&1 | tee indexd_benchmarks.txt; then
            echo "go test exited with an error"
            exit 1
          fi
      
          if grep -E 'FAIL|panic:|fatal error' indexd_benchmarks.txt; then
            echo "Detected failure pattern in benchmark output"
            exit 1
          fi

      - name: Save latest benchmark as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: latest-benchmark
          path: indexd_benchmarks.txt
          retention-days: 31
