name: Benchmark Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: indexd_benchmark
          POSTGRES_PASSWORD: indexd_benchmark
          POSTGRES_DB: indexd_benchmark
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_USER: indexd_benchmark
      POSTGRES_PASSWORD: indexd_benchmark
      POSTGRES_DB: indexd_benchmark
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run benchmarks
        run: |
          go test -run='^$' -bench=. -benchtime=1s -timeout=2h ./... 2>&1 | tee new_bench.txt

      - name: Save latest benchmark as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-benchmark
          path: new_bench.txt
